* 6809 assembly program generated by cmoc 0.1.83


	SECTION	code


_dicSize	IMPORT
_dicBitSize	IMPORT
_aheadSize	IMPORT
_aheadBitSize	IMPORT
_dicBitSize	EXPORT
_dicSize	EXPORT
_aheadBitSize	EXPORT
_aheadSize	EXPORT
___va_arg	IMPORT
_abs	IMPORT
_adddww	IMPORT
_atoi	IMPORT
_atol	IMPORT
_atoui	IMPORT
_atoul	IMPORT
_boyerMooreSearch	IMPORT
_bruteForceSearch	IMPORT
_bruteForceSearchOptim	EXPORT


*******************************************************************************

* FUNCTION bruteForceSearchOptim(): defined at lz77.c:120
_bruteForceSearchOptim	EQU	*
* Calling convention: Default
	PSHS	U
	LEAU	,S
	LEAS	-4,S
* Formal parameter(s):
*      4,U:    2 bytes: x: unsigned char *
*      6,U:    2 bytes: m: int
*      8,U:    2 bytes: y: unsigned char *
*     10,U:    2 bytes: n: int
* Local non-static variable(s):
*     -4,U:    2 bytes: yb: unsigned char *
*     -2,U:    2 bytes: i: int
* Line lz77.c:123: init of variable i
	CLRA
	CLRB
	STD	-2,U		variable i
* Line lz77.c:126: for init
* Line lz77.c:126: assignment: =
* optim: stripConsecutiveLoadsToSameReg
	LDD	8,U
	STD	-4,U
	BRA	L00096		jump to for condition
L00095	EQU	*
* Line lz77.c:126: for body
* Line lz77.c:127: if
* Line lz77.c:127: function call: memcmp()
	LDD	6,U		variable `m', declared at lz77.c:120
	PSHS	B,A		argument 3 of memcmp(): int
	LDD	8,U		variable `y', declared at lz77.c:120
	PSHS	B,A		argument 2 of memcmp(): unsigned char *
	LDD	4,U		variable `x', declared at lz77.c:120
	PSHS	B,A		argument 1 of memcmp(): unsigned char *
	LBSR	_memcmp
	LEAS	6,S
	ADDD	#0
	BNE	L00100		 (optim: condBranchOverUncondBranch)
* optim: condBranchOverUncondBranch
* Useless label L00099 removed
* Line lz77.c:128
* Line lz77.c:128: return with value
* optim: optimizeStackOperations4
* optim: optimizeStackOperations4
	LDD	8,U		variable `y', declared at lz77.c:120
	SUBD	-4,U		optim: optimizeStackOperations4
* Emitted no code to cast `unsigned int' to `int'
	BRA	L00090		return (lz77.c:128)
L00100	EQU	*		else clause of if() started at lz77.c:127
* Useless label L00101 removed
* Useless label L00097 removed
* Line lz77.c:126: for increment(s)
	LDD	8,U		variable `y', declared at lz77.c:126
	ADDD	#1
	STD	8,U
	LDD	-2,U		variable `i', declared at lz77.c:126
	ADDD	#1
	STD	-2,U
* optim: removeUselessOps
L00096	EQU	*
* Line lz77.c:126: for condition
	LDD	10,U		variable n
	SUBD	6,U		variable m
* optim: optimize16BitCompares
* optim: optimize16BitCompares
	CMPD	-2,U		optim: optimize16BitCompares
	BGE	L00095		optim: optimize16BitCompares
* optim: branchToNextLocation
* Useless label L00098 removed
* Line lz77.c:130: return with value
	LDD	#$FFFF		constant expression: 65535 decimal, signed
* optim: branchToNextLocation
L00090	EQU	*		end of bruteForceSearchOptim()
	LEAS	,U
	PULS	U,PC
* END FUNCTION bruteForceSearchOptim(): defined at lz77.c:120
funcend_bruteForceSearchOptim	EQU *
funcsize_bruteForceSearchOptim	EQU	funcend_bruteForceSearchOptim-_bruteForceSearchOptim
_bsearch	IMPORT
_cmpdww	IMPORT
_compress	EXPORT


*******************************************************************************

* FUNCTION compress(): defined at lz77.c:352
_compress	EQU	*
* Calling convention: Default
	PSHS	U
	LEAU	,S
	LEAS	-21,S
* Formal parameter(s):
*      4,U:    2 bytes: input: unsigned char *
*      6,U:    2 bytes: iSize: unsigned int
*      8,U:    2 bytes: output: unsigned char *
*     10,U:    2 bytes: oSize: unsigned int
* Local non-static variable(s):
*    -21,U:    5 bytes: t: struct tupleStruct
*    -16,U:    5 bytes: $V00094: struct tupleStruct
*    -11,U:    5 bytes: bf: struct bitFieldStruct
*     -6,U:    2 bytes: index: int
*     -4,U:    2 bytes: dicIndexStart: int
*     -2,U:    2 bytes: dicIndexStop: int
* Line lz77.c:355: function call: memset()
	LDD	10,U		variable `oSize', declared at lz77.c:352
	PSHS	B,A		argument 3 of memset(): unsigned int
	CLRA
	CLRB
	PSHS	B,A		argument 2 of memset(): int
	LDD	8,U		variable `output', declared at lz77.c:352
	PSHS	B,A		argument 1 of memset(): unsigned char *
	LBSR	_memset
	LEAS	6,S
* Line lz77.c:357: function call: initBitField()
	LDD	8,U		variable `output', declared at lz77.c:352
	PSHS	B,A		argument 2 of initBitField(): unsigned char *
	LEAX	-11,U		variable `bf', declared at lz77.c:356
	PSHS	X		argument 1 of initBitField(): struct bitFieldStruct *
	LBSR	_initBitField
	LEAS	4,S
* Line lz77.c:359: init of variable index
	CLRA
	CLRB
	STD	-6,U		variable index
* Line lz77.c:360: init of variable dicIndexStart
* optim: stripExtraClrA_B
* optim: stripExtraClrA_B
	STD	-4,U		variable dicIndexStart
* Line lz77.c:360: init of variable dicIndexStop
* optim: stripExtraClrA_B
* optim: stripExtraClrA_B
	STD	-2,U		variable dicIndexStop
* Line lz77.c:361: while
	LBRA	L00103		jump to while condition
L00102	EQU	*		while body
* Line lz77.c:363: assignment: =
* Line lz77.c:363: conditional expression
	LDD	-6,U		variable index
	SUBD	_dicSize+0,PCR	variable dicSize
	CMPD	#0
	BGE	L00106		 (optim: condBranchOverUncondBranch)
* optim: condBranchOverUncondBranch
* Useless label L00105 removed
	CLRA
	CLRB
	BRA	L00107		end of true expression of conditional
L00106	EQU	*
	LDD	-6,U		variable index
	SUBD	_dicSize+0,PCR	variable dicSize
L00107	EQU	*
	STD	-4,U
* Line lz77.c:364: assignment: =
	LDD	-6,U		variable index
	ADDD	#$FFFF		65535
	STD	-2,U
* Line lz77.c:367: init of variable t
	CLRA
	CLRB
	STD	-21,U		offset in variable t
* optim: stripExtraClrA_B
* optim: stripExtraClrA_B
	STD	-19,U		offset in variable t
* optim: stripExtraClrA_B
* optim: stripExtraClrA_B
	STB	-17,U		offset in variable t
* Line lz77.c:368: assignment: =
* Line lz77.c:368: function call: findInDic()
	LDX	_aheadSize+0,PCR	optim: transformPshsDPshsD
	PSHS	X		optim: transformPshsDPshsD
	LDY	-6,U		optim: transformPshsXPshsX
* optim: optimizePshsOps
	LDX	-2,U		optim: transformPshsDPshsD
	PSHS	Y,X		optim: optimizePshsOps
	LDY	-4,U		optim: transformPshsXPshsX
* optim: optimizePshsOps
	LDX	6,U		optim: transformPshsDPshsD
* optim: optimizePshsOps
	LDD	4,U		variable `input', declared at lz77.c:352
	PSHS	Y,X,B,A		optim: optimizePshsOps
	LEAX	-16,U		address of struct/union to be returned by findInDic()
	PSHS	X		hidden argument
	LBSR	_findInDic
	LEAS	14,S
	LEAX	-16,U		address of struct/union returned by findInDic()
	LDD	#5		size of struct tupleStruct
	PSHS	B,A		push size to _memcpy
	PSHS	X		source struct
	LEAX	-21,U		variable `t', declared at lz77.c:367
	PSHS	X
	LBSR	_memcpy		copy struct (preserves X)
	LEAS	6,S
* Line lz77.c:372: function call: writebits()
	LDB	_dicBitSize+0,PCR	variable `dicBitSize', declared at lz77.c:10
	CLRA			promoting byte argument to word
	PSHS	B,A		argument 3 of writebits(): unsigned char
	LDD	-21,U		member d of tupleStruct, via variable t
	PSHS	B,A		argument 2 of writebits(): unsigned int
	LEAX	-11,U		variable `bf', declared at lz77.c:356
	PSHS	X		argument 1 of writebits(): struct bitFieldStruct *
	LBSR	_writebits
	LEAS	6,S
* Line lz77.c:373: function call: writebits()
	LDB	_aheadBitSize+0,PCR	variable `aheadBitSize', declared at lz77.c:12
	CLRA			promoting byte argument to word
	PSHS	B,A		argument 3 of writebits(): unsigned char
	LDD	-19,U		member l of tupleStruct, via variable t
	PSHS	B,A		argument 2 of writebits(): unsigned int
	LEAX	-11,U		variable `bf', declared at lz77.c:356
	PSHS	X		argument 1 of writebits(): struct bitFieldStruct *
	LBSR	_writebits
	LEAS	6,S
* Line lz77.c:374: function call: writebits()
	CLRA
	LDB	#$08		decimal 8 signed
	PSHS	B,A		argument 3 of writebits(): int
	LDB	-17,U		member c of tupleStruct, via variable t
* optim: stripExtraClrA_B
	PSHS	B,A		argument 2 of writebits(): unsigned char
	LEAX	-11,U		variable `bf', declared at lz77.c:356
	PSHS	X		argument 1 of writebits(): struct bitFieldStruct *
	LBSR	_writebits
	LEAS	6,S
* Line lz77.c:376: assignment: +=
* optim: optimizeStackOperations4
* optim: optimizeStackOperations4
	CLRA
	LDB	#$01		decimal 1 signed
	ADDD	-19,U		optim: optimizeStackOperations4
	ADDD	-6,U		optim: pushDLoadAdd
* 
* 
	STD	-6,U
L00103	EQU	*		while condition at lz77.c:361
	LDD	-6,U		variable index
	CMPD	6,U		variable iSize
	LBLO	L00102
* optim: branchToNextLocation
* Useless label L00104 removed
* Line lz77.c:378: return with value
	LDD	-9,U		member currentIndex of bitFieldStruct, via variable bf
* Emitted no code to cast `unsigned int' to `int'
* optim: branchToNextLocation
* Useless label L00092 removed
	LEAS	,U
	PULS	U,PC
* END FUNCTION compress(): defined at lz77.c:352
funcend_compress	EQU *
funcsize_compress	EQU	funcend_compress-_compress
_delay	IMPORT
_divdwb	IMPORT
_divdww	IMPORT
_divmod16	IMPORT
_divmod8	IMPORT
_dwtoa	IMPORT
_enableCMOCFloatSupport	IMPORT
_exit	IMPORT
_findInDic	EXPORT


*******************************************************************************

* FUNCTION findInDic(): defined at lz77.c:323
_findInDic	EQU	*
* Calling convention: Default
	PSHS	U
	LEAU	,S
	LEAS	-14,S
* Formal parameter(s):
*      6,U:    2 bytes: input: unsigned char *
*      8,U:    2 bytes: inputSize: unsigned int
*     10,U:    2 bytes: startDicIndex: unsigned int
*     12,U:    2 bytes: stopDicIndex: unsigned int
*     14,U:    2 bytes: startAHead: unsigned int
*     16,U:    2 bytes: aHeadSize: unsigned int
* Local non-static variable(s):
*    -11,U:    2 bytes: i: unsigned int
*     -9,U:    5 bytes: t: struct tupleStruct
*     -4,U:    2 bytes: match: int
*     -2,U:    2 bytes: maxAHeadIndex: unsigned int
* Line lz77.c:326: if
	LDD	14,U		variable startAHead
	CMPD	10,U		variable startDicIndex
	BEQ	L00108
* optim: branchToNextLocation
* Useless label L00110 removed
	LDD	10,U		variable startDicIndex
	CMPD	12,U		variable stopDicIndex
	BNE	L00109		 (optim: condBranchOverUncondBranch)
* optim: condBranchOverUncondBranch
L00108	EQU	*		then clause of if() started at lz77.c:326
* Line lz77.c:326
* Line lz77.c:328: init of variable t
	CLRA
	CLRB
	STD	-14,U		offset in variable t
* optim: stripExtraClrA_B
* optim: stripExtraClrA_B
	STD	-12,U		offset in variable t
	LDD	14,U		variable startAHead
	LDX	6,U		pointer input
* optimizeLoadDX
	LDB	D,X		get r-value
	STB	-10,U		offset in variable t
* Line lz77.c:329: return struct/union by value
	LEAX	-14,U		variable `t', declared at lz77.c:328
	PSHS	X		source struct/union
	LDX	4,U		address of return value
	LDD	#5		size of struct tupleStruct
	LBSR	copyMem
	LEAS	2,S		discard copyMem argument
	LBRA	L00091		return (lz77.c:329)
L00109	EQU	*		else clause of if() started at lz77.c:326
* Useless label L00111 removed
* Line lz77.c:332: init of variable t
	CLRA
	CLRB
	STD	-9,U		offset in variable t
* optim: stripExtraClrA_B
* optim: stripExtraClrA_B
	STD	-7,U		offset in variable t
	LDD	14,U		variable startAHead
	LDX	6,U		pointer input
* optimizeLoadDX
	LDB	D,X		get r-value
	STB	-5,U		offset in variable t
* Line lz77.c:333: init of variable match
	LDD	#$FFFF		65535
	STD	-4,U		variable match
* Line lz77.c:336: init of variable maxAHeadIndex
* Line lz77.c:336: conditional expression
* optim: optimizeStackOperations4
* optim: optimizeStackOperations4
	LDD	14,U		variable startAHead
	ADDD	_aheadSize+0,PCR	variable aheadSize
	CMPD	8,U		optim: optimizeStackOperations4
	BLS	L00113		 (optim: condBranchOverUncondBranch)
* optim: condBranchOverUncondBranch
* Useless label L00112 removed
* optim: stripOpToDeadReg
* optim: stripOpToDeadReg
* PSHS B,A optim: optimizeStackOperations1
	LDD	8,U		variable inputSize
	SUBD	14,U		variable startAHead
	SUBD	#1		optim: optimizeStackOperations1
	BRA	L00114		end of true expression of conditional
L00113	EQU	*
	LDD	16,U		variable aHeadSize
	ADDD	#$FFFF		65535
L00114	EQU	*
	STD	-2,U		variable maxAHeadIndex
* Line lz77.c:338: for init
* Line lz77.c:338: init of variable i
* optim: storeLoad
	STD	-11,U		variable i
	BRA	L00116		jump to for condition
L00115	EQU	*
* Line lz77.c:338: for body
* Line lz77.c:339: assignment: =
* Line lz77.c:339: function call: bruteForceSearchOptim()
	LDD	12,U		variable stopDicIndex
	SUBD	10,U		variable startDicIndex
	PSHS	B,A		argument 4 of bruteForceSearchOptim(): unsigned int
* optim: optimizeStackOperations4
* optim: optimizeStackOperations4
	LDD	6,U		variable `input', declared at lz77.c:323
	ADDD	10,U		optim: optimizeStackOperations4
	PSHS	B,A		argument 3 of bruteForceSearchOptim(): unsigned char *
	LDD	-11,U		variable `i', declared at lz77.c:338
	PSHS	B,A		argument 2 of bruteForceSearchOptim(): unsigned int
* optim: optimizeStackOperations4
* optim: optimizeStackOperations4
	LDD	6,U		variable `input', declared at lz77.c:323
	ADDD	14,U		optim: optimizeStackOperations4
	PSHS	B,A		argument 1 of bruteForceSearchOptim(): unsigned char *
	LBSR	_bruteForceSearchOptim
	LEAS	8,S
	STD	-4,U
* Line lz77.c:340: if
* optim: storeLoad
	ADDD	#0
	BLT	L00120		 (optim: condBranchOverUncondBranch)
* optim: condBranchOverUncondBranch
* Useless label L00119 removed
* Line lz77.c:340
* Line lz77.c:341: assignment: =
* optim: optimize16BitStackOps1
* optim: optimize16BitStackOps1
* optim: stripOpToDeadReg
* optim: stripOpToDeadReg
* PSHS B,A optim: optimizeStackOperations1
	LDD	12,U		variable stopDicIndex
	SUBD	10,U		variable startDicIndex
	ADDD	#1		optim: optimizeStackOperations1
	SUBD	-4,U		optim: optimize16BitStackOps1
* optim: stripUselessPushPull
* optim: optimizeLeax
* optim: stripUselessPushPull
	STD	-9,U		optim: optimizeLeax
* Line lz77.c:342: assignment: =
	LDD	-11,U		variable `i', declared at lz77.c:338
* optim: stripUselessPushPull
* optim: optimizeLeax
* optim: stripUselessPushPull
	STD	-7,U		optim: optimizeLeax
* Line lz77.c:343: assignment: =
	LDD	14,U		variable startAHead
	ADDD	-11,U		variable i
	LDX	6,U		pointer input
* optimizeLoadDX
	LDB	D,X		get r-value
* optim: stripExtraPushPullB
* optim: optimizeLeax
* optim: stripExtraPushPullB
	STB	-5,U		optim: optimizeLeax
	BRA	L00118		break
L00120	EQU	*		else clause of if() started at lz77.c:340
* Useless label L00121 removed
* Useless label L00117 removed
* Line lz77.c:338: for increment(s)
	LDD	-11,U
	SUBD	#1
	STD	-11,U
L00116	EQU	*
* Line lz77.c:338: for condition
	LDD	-11,U		variable i
	CMPD	#$01
	BHS	L00115
* optim: branchToNextLocation
L00118	EQU	*		end for
* Line lz77.c:348: return struct/union by value
	LEAX	-9,U		variable `t', declared at lz77.c:332
	PSHS	X		source struct/union
	LDX	4,U		address of return value
	LDD	#5		size of struct tupleStruct
	LBSR	copyMem
	LEAS	2,S		discard copyMem argument
* optim: branchToNextLocation
L00091	EQU	*		end of findInDic()
	LEAS	,U
	PULS	U,PC
* END FUNCTION findInDic(): defined at lz77.c:323
funcend_findInDic	EQU *
funcsize_findInDic	EQU	funcend_findInDic-_findInDic
_initBitField	EXPORT


*******************************************************************************

* FUNCTION initBitField(): defined at lz77.c:47
_initBitField	EQU	*
* Calling convention: Default
	PSHS	U
	LEAU	,S
* Formal parameter(s):
*      4,U:    2 bytes: bf: struct bitFieldStruct *
*      6,U:    2 bytes: buf: unsigned char *
* Line lz77.c:49: assignment: =
	CLRA
	LDB	#$07		decimal 7 signed
* optim: stripExtraPushPullB
	LDX	4,U		variable bf
* optim: optimizeLeax
* optim: stripExtraPushPullB
	STB	4,X		optim: optimizeLeax
* Line lz77.c:50: assignment: =
* optim: stripExtraClrA_B
	CLRB
* optim: stripUselessPushPull
	LDX	4,U		variable bf
* optim: optimizeLeax
* optim: stripUselessPushPull
	STD	2,X		optim: optimizeLeax
* Line lz77.c:51: assignment: =
	LDD	6,U		variable `buf', declared at lz77.c:47
* optim: stripUselessPushPull
* optim: optimizeLdx
* optim: stripUselessPushPull
	STD	[4,U]		optim: optimizeLdx
* Useless label L00087 removed
	LEAS	,U
	PULS	U,PC
* END FUNCTION initBitField(): defined at lz77.c:47
funcend_initBitField	EQU *
funcsize_initBitField	EQU	funcend_initBitField-_initBitField
_initDefaultParameters	EXPORT


*******************************************************************************

* FUNCTION initDefaultParameters(): defined at lz77.c:21
_initDefaultParameters	EQU	*
* Calling convention: Default
* Line lz77.c:23: assignment: =
	LDD	#$0FFF		decimal 4095 signed
	STD	_dicSize+0,PCR
* Line lz77.c:24: assignment: =
	LDB	#$0C
	STB	_dicBitSize+0,PCR	variable dicBitSize
* Line lz77.c:25: assignment: =
	CLRA
	LDB	#$3F		decimal 63 signed
	STD	_aheadSize+0,PCR
* Line lz77.c:26: assignment: =
	LDB	#$06
	STB	_aheadBitSize+0,PCR	variable aheadBitSize
* Useless label L00085 removed
	RTS
* END FUNCTION initDefaultParameters(): defined at lz77.c:21
funcend_initDefaultParameters	EQU *
funcsize_initDefaultParameters	EQU	funcend_initDefaultParameters-_initDefaultParameters
_initParameters	EXPORT


*******************************************************************************

* FUNCTION initParameters(): defined at lz77.c:34
_initParameters	EQU	*
* Calling convention: Default
	PSHS	U
	LEAU	,S
* Formal parameter(s):
*      4,U:    2 bytes: dsz: unsigned int
*      7,U:    1 byte : bdsz: unsigned char
*      8,U:    2 bytes: asz: unsigned int
*     11,U:    1 byte : basz: unsigned char
* Line lz77.c:36: assignment: =
* optim: stripConsecutiveLoadsToSameReg
	LDD	4,U
	STD	_dicSize+0,PCR
* Line lz77.c:37: assignment: =
	LDB	7,U		variable `bdsz', declared at lz77.c:34
	STB	_dicBitSize+0,PCR
* Line lz77.c:38: assignment: =
* optim: stripConsecutiveLoadsToSameReg
	LDD	8,U
	STD	_aheadSize+0,PCR
* Line lz77.c:39: assignment: =
	LDB	11,U		variable `basz', declared at lz77.c:34
	STB	_aheadBitSize+0,PCR
* Useless label L00086 removed
	LEAS	,U
	PULS	U,PC
* END FUNCTION initParameters(): defined at lz77.c:34
funcend_initParameters	EQU *
funcsize_initParameters	EQU	funcend_initParameters-_initParameters
_isalnum	IMPORT
_isalpha	IMPORT
_isdigit	IMPORT
_isspace	IMPORT
_itoa10	IMPORT
_karpRabinSearch	IMPORT
_knuthMorrisPrattSearch	IMPORT
_labs	IMPORT
_ltoa10	IMPORT
_memchr	IMPORT
_memcmp	IMPORT
_memcpy	IMPORT
_memichr	IMPORT
_memicmp	IMPORT
_memmove	IMPORT
_memset	IMPORT
_memset16	IMPORT
_mulwb	IMPORT
_mulww	IMPORT
_printf	IMPORT
_putchar	IMPORT
_putstr	IMPORT
_qsort	IMPORT
_rand	IMPORT
_readbits	EXPORT


*******************************************************************************

* FUNCTION readbits(): defined at lz77.c:80
_readbits	EQU	*
* Calling convention: Default
	PSHS	U
	LEAU	,S
	LEAS	-6,S
* Formal parameter(s):
*      4,U:    2 bytes: bf: struct bitFieldStruct *
*      7,U:    1 byte : bitCount: unsigned char
* Local non-static variable(s):
*     -6,U:    1 byte : mask: unsigned char
*     -5,U:    2 bytes: value: unsigned int
*     -3,U:    2 bytes: currentBit: unsigned int
*     -1,U:    1 byte : bitSet: unsigned char
* Line lz77.c:83: init of variable mask
	CLR	-6,U		variable mask
* Line lz77.c:84: init of variable value
	CLRA
	CLRB
	STD	-5,U		variable value
* Line lz77.c:85: init of variable currentBit
* optim: stripExtraClrA_B
* optim: stripExtraClrA_B
	STD	-3,U		variable currentBit
* Line lz77.c:86: init of variable bitSet
	CLR	-1,U		variable bitSet
* Line lz77.c:87: while
	LBRA	L00123		jump to while condition
L00122	EQU	*		while body
* Line lz77.c:88: assignment: =
	CLRA
	LDB	#$01		decimal 1 signed
	PSHS	B,A		left side of shift: used and popped by shiftLeft
	LDX	4,U		variable bf
	LDB	4,X		member bitLeft of bitFieldStruct
* optim: stripExtraClrA_B
	LBSR	shiftLeft
* Cast from `int' to byte: result already in B
	STB	-6,U
* Line lz77.c:89: assignment: =
* optim: storeLoad
	PSHS	B
	LDX	4,U		variable bf
	LDD	2,X		member currentIndex of bitFieldStruct
	PSHS	B,A		preserve array index
	LDX	4,U		variable bf
	LDD	,X		member buffer of bitFieldStruct
	ADDD	,S++		add stacked array index to array address in D
	TFR	D,X		put resulting address in X
	LDB	,X		get r-value
	ANDB	,S+
	PSHS	B		left side of shift: used and popped by shiftByteRightUnsigned
	LDX	4,U		variable bf
	LDB	4,X		member bitLeft of bitFieldStruct
	CLRA
	LBSR	shiftByteRightUnsigned
	CLRA
	STD	-3,U
* Line lz77.c:90: assignment: |=
* optim: storeLoad
	PSHS	B,A		left side of shift: used and popped by shiftLeft
	LDB	-1,U		variable `bitSet', declared at lz77.c:86
* optim: stripExtraClrA_B
	LBSR	shiftLeft
	PSHS	B,A
	LEAX	-5,U
	LDD	,S++
	ORA	,X
	ORB	1,X
	STD	,X
* Line lz77.c:91: post-decrement
	DEC	7,U
* Line lz77.c:92: post-increment
	INC	-1,U
* Line lz77.c:93: post-decrement
	LDX	4,U		variable bf
* optim: optimizeLeax
	DEC	4,X		optim: optimizeLeax
* Line lz77.c:94: if
	LDX	4,U		variable bf
	LDB	4,X		member bitLeft of bitFieldStruct
	CMPB	#0
	BGE	L00126		 (optim: condBranchOverUncondBranch)
* optim: condBranchOverUncondBranch
* Useless label L00125 removed
* Line lz77.c:94
* Line lz77.c:95: assignment: =
	CLRA
* LDB #$07 optim: optimizeStackOperations1
* PSHS B optim: optimizeStackOperations1
	LDX	4,U		variable bf
* optim: optimizeLeax
	LDB	#7		optim: optimizeStackOperations1
	STB	4,X		optim: optimizeLeax
* Line lz77.c:96: post-increment
	LDX	4,U		variable bf
	LEAX	2,X		member currentIndex of bitFieldStruct
	LDD	,X
	ADDD	#1
	STD	,X
L00126	EQU	*		else clause of if() started at lz77.c:94
* Useless label L00127 removed
L00123	EQU	*		while condition at lz77.c:87
	LDB	7,U		variable `bitCount', declared at lz77.c:80
* optim: loadCmpZeroBeqOrBne
	LBNE	L00122
* optim: branchToNextLocation
* Useless label L00124 removed
* Line lz77.c:99: return with value
	LDD	-5,U		variable `value', declared at lz77.c:84
* optim: branchToNextLocation
* Useless label L00089 removed
	LEAS	,U
	PULS	U,PC
* END FUNCTION readbits(): defined at lz77.c:80
funcend_readbits	EQU *
funcsize_readbits	EQU	funcend_readbits-_readbits
_readline	IMPORT
_readword	IMPORT
_sbrk	IMPORT
_sbrkmax	IMPORT
_setConsoleOutHook	IMPORT
_set_null_ptr_handler	IMPORT
_set_stack_overflow_handler	IMPORT
_sprintf	IMPORT
_sqrt16	IMPORT
_sqrt32	IMPORT
_srand	IMPORT
_strcat	IMPORT
_strchr	IMPORT
_strcmp	IMPORT
_strcpy	IMPORT
_stricmp	IMPORT
_strlen	IMPORT
_strlwr	IMPORT
_strncmp	IMPORT
_strncpy	IMPORT
_strstr	IMPORT
_strtol	IMPORT
_strtoul	IMPORT
_strupr	IMPORT
_subdww	IMPORT
_tolower	IMPORT
_toupper	IMPORT
_ultoa10	IMPORT
_uncompress	EXPORT


*******************************************************************************

* FUNCTION uncompress(): defined at lz77.c:382
_uncompress	EQU	*
* Calling convention: Default
	PSHS	U
	LEAU	,S
	LEAS	-12,S
* Formal parameter(s):
*      4,U:    2 bytes: input: unsigned char *
*      6,U:    2 bytes: iSize: unsigned int
*      8,U:    2 bytes: output: unsigned char *
*     10,U:    2 bytes: oSize: unsigned int
* Local non-static variable(s):
*    -12,U:    5 bytes: t: struct tupleStruct
*     -7,U:    5 bytes: bf: struct bitFieldStruct
*     -2,U:    2 bytes: outputIdx: int
* Line lz77.c:385: function call: initBitField()
	LDD	4,U		variable `input', declared at lz77.c:382
	PSHS	B,A		argument 2 of initBitField(): unsigned char *
	LEAX	-7,U		variable `bf', declared at lz77.c:384
	PSHS	X		argument 1 of initBitField(): struct bitFieldStruct *
	LBSR	_initBitField
	LEAS	4,S
* Line lz77.c:386: init of variable outputIdx
	CLRA
	CLRB
	STD	-2,U		variable outputIdx
* Line lz77.c:387: function call: memset()
	LDD	10,U		variable `oSize', declared at lz77.c:382
	PSHS	B,A		argument 3 of memset(): unsigned int
	CLRA
	CLRB
	PSHS	B,A		argument 2 of memset(): int
	LDD	8,U		variable `output', declared at lz77.c:382
	PSHS	B,A		argument 1 of memset(): unsigned char *
	LBSR	_memset
	LEAS	6,S
* Line lz77.c:389: while
	LBRA	L00129		jump to while condition
L00128	EQU	*		while body
* Line lz77.c:392: assignment: =
* Line lz77.c:392: function call: readbits()
	LDB	_dicBitSize+0,PCR	variable `dicBitSize', declared at lz77.c:10
	CLRA			promoting byte argument to word
	PSHS	B,A		argument 2 of readbits(): unsigned char
	LEAX	-7,U		variable `bf', declared at lz77.c:384
	PSHS	X		argument 1 of readbits(): struct bitFieldStruct *
	LBSR	_readbits
	LEAS	4,S
* optim: stripUselessPushPull
* optim: optimizeLeax
* optim: stripUselessPushPull
	STD	-12,U		optim: optimizeLeax
* Line lz77.c:393: assignment: =
* Line lz77.c:393: function call: readbits()
	LDB	_aheadBitSize+0,PCR	variable `aheadBitSize', declared at lz77.c:12
	CLRA			promoting byte argument to word
	PSHS	B,A		argument 2 of readbits(): unsigned char
	LEAX	-7,U		variable `bf', declared at lz77.c:384
	PSHS	X		argument 1 of readbits(): struct bitFieldStruct *
	LBSR	_readbits
	LEAS	4,S
* optim: stripUselessPushPull
* optim: optimizeLeax
* optim: stripUselessPushPull
	STD	-10,U		optim: optimizeLeax
* Line lz77.c:394: assignment: =
* Line lz77.c:394: function call: readbits()
	CLRA
	LDB	#$08		decimal 8 signed
	PSHS	B,A		argument 2 of readbits(): int
	LEAX	-7,U		variable `bf', declared at lz77.c:384
	PSHS	X		argument 1 of readbits(): struct bitFieldStruct *
	LBSR	_readbits
	LEAS	4,S
* Cast from `unsigned int' to byte: result already in B
* optim: stripExtraPushPullB
* optim: optimizeLeax
* optim: stripExtraPushPullB
	STB	-8,U		optim: optimizeLeax
* Line lz77.c:397: if
	LDD	-12,U		member d of tupleStruct, via variable t
* optim: loadCmpZeroBeqOrBne
	BEQ	L00132		 (optim: condBranchOverUncondBranch)
* optim: condBranchOverUncondBranch
* Useless label L00131 removed
* Line lz77.c:397
* Line lz77.c:399: function call: memcpy()
	LDD	-10,U		member l of tupleStruct, via variable t
	PSHS	B,A		argument 3 of memcpy(): unsigned int
* optim: optimizeStackOperations4
* optim: optimizeStackOperations4
* optim: optimizeStackOperations4
* optim: optimizeStackOperations4
	LDD	8,U		variable `output', declared at lz77.c:382
	ADDD	-2,U		optim: optimizeStackOperations4
	SUBD	-12,U		optim: optimizeStackOperations4
	PSHS	B,A		argument 2 of memcpy(): unsigned char *
* optim: optimizeStackOperations4
* optim: optimizeStackOperations4
	LDD	8,U		variable `output', declared at lz77.c:382
	ADDD	-2,U		optim: optimizeStackOperations4
	PSHS	B,A		argument 1 of memcpy(): unsigned char *
	LBSR	_memcpy
	LEAS	6,S
* Line lz77.c:400: assignment: +=
* optim: optimizeStackOperations4
* optim: optimizeStackOperations4
	LDD	-2,U
	ADDD	-10,U		optim: optimizeStackOperations4
	STD	-2,U
L00132	EQU	*		else clause of if() started at lz77.c:397
* Useless label L00133 removed
* Line lz77.c:403: assignment: =
	LDB	-8,U		member c of tupleStruct, via variable t
	PSHS	B
	LDD	-2,U		variable `outputIdx', declared at lz77.c:403
	ADDD	#1
	STD	-2,U
	SUBD	#1		post increment yields initial value
	LDX	8,U		pointer output
	LEAX	D,X		add offset
	LDB	,S+
	STB	,X
L00129	EQU	*		while condition at lz77.c:389
* optim: optimizeStackOperations4
* optim: optimizeStackOperations4
	LDD	-5,U		member currentIndex of bitFieldStruct, via variable bf
	CMPD	6,U		optim: optimizeStackOperations4
	LBLO	L00128
* optim: branchToNextLocation
* Useless label L00130 removed
* Line lz77.c:405: return with value
	LDD	-2,U		variable `outputIdx', declared at lz77.c:386
* optim: branchToNextLocation
* Useless label L00093 removed
	LEAS	,U
	PULS	U,PC
* END FUNCTION uncompress(): defined at lz77.c:382
funcend_uncompress	EQU *
funcsize_uncompress	EQU	funcend_uncompress-_uncompress
_utoa10	IMPORT
_vprintf	IMPORT
_vsprintf	IMPORT
_writebits	EXPORT


*******************************************************************************

* FUNCTION writebits(): defined at lz77.c:54
_writebits	EQU	*
* Calling convention: Default
	PSHS	U
	LEAU	,S
	LEAS	-2,S
* Formal parameter(s):
*      4,U:    2 bytes: bf: struct bitFieldStruct *
*      6,U:    2 bytes: value: unsigned int
*      9,U:    1 byte : bitCount: unsigned char
* Local non-static variable(s):
*     -2,U:    1 byte : i: unsigned char
*     -1,U:    1 byte : bitSet: unsigned char
* Line lz77.c:58: init of variable bitSet
	CLR	-1,U		variable bitSet
* Line lz77.c:59: while
	LBRA	L00135		jump to while condition
L00134	EQU	*		while body
* Line lz77.c:60: init of variable currentBit
	LDD	6,U		variable value
	CLRA			optim: andA_B0
	ANDB	#$01
* Cast from `unsigned int' to byte: result already in B
	STB	-2,U		variable currentBit
* Line lz77.c:61: assignment: |=
* optim: storeLoad
	PSHS	B		left side of shift: used and popped by shiftByteLeft
	LDX	4,U		variable bf
	LDB	4,X		member bitLeft of bitFieldStruct
* optim: stripExtraClrA_B
	LBSR	shiftByteLeft
	PSHS	B
	LDX	4,U		variable bf
	LDD	2,X		member currentIndex of bitFieldStruct
	PSHS	B,A		preserve array index
	LDX	4,U		variable bf
	LDD	,X		member buffer of bitFieldStruct
	ADDD	,S++		add stacked array index to array address in D
	TFR	D,X		put resulting address in X
	LDB	,X
	ORB	,S+
	STB	,X
* Line lz77.c:62: post-decrement
	LDX	4,U		variable bf
* optim: optimizeLeax
	DEC	4,X		optim: optimizeLeax
* Line lz77.c:63: if
	LDX	4,U		variable bf
	LDB	4,X		member bitLeft of bitFieldStruct
	CMPB	#0
	BGE	L00138		 (optim: condBranchOverUncondBranch)
* optim: condBranchOverUncondBranch
* Useless label L00137 removed
* Line lz77.c:63
* Line lz77.c:64: assignment: =
	CLRA
* LDB #$07 optim: optimizeStackOperations1
* PSHS B optim: optimizeStackOperations1
	LDX	4,U		variable bf
* optim: optimizeLeax
	LDB	#7		optim: optimizeStackOperations1
	STB	4,X		optim: optimizeLeax
* Line lz77.c:65: post-increment
	LDX	4,U		variable bf
	LEAX	2,X		member currentIndex of bitFieldStruct
	LDD	,X
	ADDD	#1
	STD	,X
L00138	EQU	*		else clause of if() started at lz77.c:63
* Useless label L00139 removed
* Line lz77.c:67: post-increment
	INC	-1,U
* Line lz77.c:68: assignment: =
	LDD	6,U		variable `value', declared at lz77.c:54
	LSRA
	RORB
	STD	6,U
L00135	EQU	*		while condition at lz77.c:59
	LDD	6,U		variable `value', declared at lz77.c:54
* optim: loadCmpZeroBeqOrBne
	LBNE	L00134
* optim: branchToNextLocation
* Useless label L00136 removed
* Line lz77.c:70: for init
* Line lz77.c:70: init of variable i
	CLR	-2,U		variable i
	BRA	L00141		jump to for condition
L00140	EQU	*
* Line lz77.c:70: for body
* Line lz77.c:71: assignment: |=
	CLRA
	CLRB
	PSHS	B,A		left side of shift: used and popped by shiftLeft
	LDX	4,U		variable bf
	LDB	4,X		member bitLeft of bitFieldStruct
* optim: stripExtraClrA_B
	LBSR	shiftLeft
* Cast from `int' to byte: result already in B
	PSHS	B
	LDX	4,U		variable bf
	LDD	2,X		member currentIndex of bitFieldStruct
	PSHS	B,A		preserve array index
	LDX	4,U		variable bf
	LDD	,X		member buffer of bitFieldStruct
	ADDD	,S++		add stacked array index to array address in D
	TFR	D,X		put resulting address in X
	LDB	,X
	ORB	,S+
	STB	,X
* Line lz77.c:72: post-decrement
	LDX	4,U		variable bf
* optim: optimizeLeax
	DEC	4,X		optim: optimizeLeax
* Line lz77.c:73: if
	LDX	4,U		variable bf
	LDB	4,X		member bitLeft of bitFieldStruct
	CMPB	#0
	BGE	L00145		 (optim: condBranchOverUncondBranch)
* optim: condBranchOverUncondBranch
* Useless label L00144 removed
* Line lz77.c:73
* Line lz77.c:74: assignment: =
	CLRA
* LDB #$07 optim: optimizeStackOperations1
* PSHS B optim: optimizeStackOperations1
	LDX	4,U		variable bf
* optim: optimizeLeax
	LDB	#7		optim: optimizeStackOperations1
	STB	4,X		optim: optimizeLeax
* Line lz77.c:75: post-increment
	LDX	4,U		variable bf
	LEAX	2,X		member currentIndex of bitFieldStruct
	LDD	,X
	ADDD	#1
	STD	,X
L00145	EQU	*		else clause of if() started at lz77.c:73
* Useless label L00146 removed
* Useless label L00142 removed
* Line lz77.c:70: for increment(s)
	INC	-2,U
L00141	EQU	*
* Line lz77.c:70: for condition
	LDB	9,U		variable bitCount
	SUBB	-1,U		variable bitSet
	PSHS	B
	LDB	-2,U		variable `i', declared at lz77.c:70
	CMPB	,S+		compare with LSB
	LBLO	L00140
* optim: branchToNextLocation
* Useless label L00143 removed
* Useless label L00088 removed
	LEAS	,U
	PULS	U,PC
* END FUNCTION writebits(): defined at lz77.c:54
funcend_writebits	EQU *
funcsize_writebits	EQU	funcend_writebits-_writebits
_zerodw	IMPORT


	ENDSECTION




	SECTION	initgl




*******************************************************************************

* Initialize global variables.


	ENDSECTION




	SECTION	rodata


string_literals_start	EQU	*
string_literals_end	EQU	*


*******************************************************************************

* READ-ONLY GLOBAL VARIABLES


	ENDSECTION




	SECTION	rwdata


* Statically-initialized global variables
* Statically-initialized local static variables


	ENDSECTION




	SECTION	bss


bss_start	EQU	*
* Uninitialized global variables
_dicBitSize	EQU	*
	RMB	1		dicBitSize
_dicSize	EQU	*
	RMB	2		dicSize
_aheadBitSize	EQU	*
	RMB	1		aheadBitSize
_aheadSize	EQU	*
	RMB	2		aheadSize
* Uninitialized local static variables
bss_end	EQU	*


	ENDSECTION




*******************************************************************************

* Importing 7 utility routine(s).
_memcmp	IMPORT
_memcpy	IMPORT
_memset	IMPORT
copyMem	IMPORT
shiftByteLeft	IMPORT
shiftByteRightUnsigned	IMPORT
shiftLeft	IMPORT


*******************************************************************************

	END
